# -- Theme Options --
# These options control how the theme functions and allow you to
# customise the display of your website.
#
# Refer to the theme docs for more details about each of these parameters.
# https://jpanther.github.io/congo/docs/configuration/#theme-parameters


colorScheme = "cherry"
defaultAppearance = "dark" # valid options: light or dark
autoSwitchAppearance = false

enableSearch = true
enableCodeCopy = true
enableImageLazyLoading = false

# robots = ""
fingerprintAlgorithm = "sha256"

[header]
  layout = "basic" # valid options: basic, hamburger, hybrid, custom
  #logo = "img/logo.jpg"
  #logoDark = "img/dark-logo.jpg"
  showTitle = true

[footer]
  showCopyright = true
  showScrollToTop = true
  showThemeAttribution = true
  showAppearanceSwitcher = true
  

[homepage]
  layout = "profile" 
  showRecent = false
  recentLimit = 5

[article]
  showScrollToTop = true
  showDate = true
  showDateUpdated = false
  showAuthor = true
  showBreadcrumbs = true
  showDraftLabel = true
  showEdit = false
  # editURL = "https://github.com/username/repo/"
  editAppendPath = true
  showHeadingAnchors = true
  showPagination = true
  invertPagination = true
  showReadingTime = true
  showTableOfContents = true
  showTaxonomies = true
  showWordCount = true
  showComments = false
  # sharingLinks = ["twitter", "mastodon", "pinterest", "reddit"]

[list]
  showScrollToTop = true
  showBreadcrumbs = true
  showSummary = true
  showTableOfContents = true
  showTaxonomies = true
  groupByYear = true
  paginationWidth = 1

[sitemap]
  excludedKinds = ["taxonomy", "term"]

[taxonomy]
  showTermCount = true

[verification]
  # google = ""
  # bing = ""
  # pinterest = ""
  # yandex = ""
